### ISSUE TITLE
Error in the Uninstall Script

### ISSUE THREAD

**Issue by jrkirkpatrick** [dotmailer/dotmailer-for-woocommerce#10]
When trying to uninstall this plug in WordPress is throwing back an Internal Server Error. 

A bit of research showed that there is likely an error in the uninstall file.

**Comment by simon-letch** [comment]
Hello,

We've tried to replicate the error you've experienced but haven't been able to.

Do you have any logs detailing the error?

Cheers,
Simon

**Comment by jrkirkpatrick** [comment]
Hello,

I was getting a PHP error initially, which I’ve logged (but I know what the issue is there and it’s nothing to do with the plug in) so I tried to delete it and I’m getting:

[cid:image001.png@01D37599.FDFE3DA0]

Unfortunately I can’t get much more than this.

Thanks

**Comment by simon-letch** [comment]
I can't see the image. Can you host it somewhere so we can see it?
